"""empty message

Revision ID: d5ed9b98b466
Revises: 
Create Date: 2023-04-26 10:06:29.774598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ed9b98b466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_power',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限编号'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='权限名称'),
    sa.Column('type', sa.String(length=1), nullable=True, comment='权限类型'),
    sa.Column('code', sa.String(length=30), nullable=True, comment='权限标识'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='权限路径'),
    sa.Column('open_type', sa.String(length=10), nullable=True, comment='打开方式'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父类编号'),
    sa.Column('icon', sa.String(length=128), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否开启'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='角色名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='角色标识'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('details', sa.String(length=255), nullable=True, comment='详情'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用¬户名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('password_hash', sa.String(length=128), nullable=True, comment='哈希密码'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='启用'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role_power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('power_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['power_id'], ['admin_power.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_user_role')
    op.drop_table('admin_role_power')
    op.drop_table('admin_user')
    op.drop_table('admin_role')
    op.drop_table('admin_power')
    # ### end Alembic commands ###
